iOS fixes
FokkeZB/Tracker pull request #28
Opened 2018-02-05 13:28 UTC by kassemitani

iOS fixes

2018-02-05 13:40 UTC, FokkeZB requested changes
Thanks for the PR! Could you stick with 2 spaces for the XML so that I can see the actual changes you made?

2018-02-05 13:55 UTC, kassemitani commented
Now its okay?

2018-02-06 14:51 UTC, FokkeZB requested changes
Almost there. Just some whitespace issues.

Thanks!

2018-02-06 14:51 UTC, FokkeZB commented on tiapp.xml
> +</ti:app>
Please make sure there's newline at the EOF.

2018-02-06 14:51 UTC, FokkeZB commented on tiapp.xml
> +		<key>NSLocationAlwaysUsageDescription</key>
Fix identation

2018-02-07 14:05 UTC, kassemitani commented
done

2018-02-08 14:02 UTC, merged

2018-02-08 14:03 UTC, FokkeZB commented
Thanks @kassemitani - it was missing the OEF newline again, but let's not bother :D